backend:
  name: github
  repo: enriquezm/engineering-portfolio

media_folder: static/assets
public_folder: assets

collections:
  - name: project
    label: Project
    folder: projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
