backend:
  name: github
  repo: enriquezm/engineering-portfolio

media_folder: static/assets
public_folder: assets

collections:
  - name: project
    label: Project
    folder: 'blog/projects'
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: source, label: Source }
      - { name: demo, label: Demo }
      - { name: body, label: Body, widget: markdown }
  - name: concept
    label: Concept
    folder: 'blog/concepts'
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
